name: Visual Studio Codespaces Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    if: ${{github.repository_owner == 'libnet' && github.ref_name == 'master'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/metadata-action@v5
      id: meta
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/libnet/libnet-vscode
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
        labels: |
          org.opencontainers.image.source=https://github.com/libnet/libnet/tree/${{ github.sha }}/
    - uses: docker/setup-buildx-action@v3
    - name: Log in to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v5
      with:
        context: .
        file: .devcontainer/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
